services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    restart: always
    networks:
      - dbnet
    ports:
      - "80:80"
    volumes:
      - ./breakfast_lecture_planner/staticfiles:/app/www/breakfast_lecture_planner/staticfiles
      - ./breakfast_lecture_planner/media:/app/www/breakfast_lecture_planner/media
      - ./breakfast_lecture_planner/logs:/var/log/nginx  # ← изменил путь логов
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - breakfast_lecture_planner
  
  breakfast_lecture_planner:
    build: ./breakfast_lecture_planner
    image: breakfast_lecture_planner
    container_name: breakfast_lecture_planner_container
    restart: always
    command: "gunicorn -c gunicorn.py breakfast_lecture_planner.wsgi"
    env_file:
      - .env
    links:
      - "postgres:dbps"
    networks:
      - dbnet
    volumes:
      - ./breakfast_lecture_planner:/app/www/breakfast_lecture_planner
      - ./breakfast_lecture_planner/media:/app/www/breakfast_lecture_planner/media:rw
    depends_on:
      - postgres
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    links:
      - "postgres:db"
    networks:
      - dbnet
    depends_on:
      - postgres
  postgres:
    image: postgres:17-alpine
    container_name: psgr
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - dbnet
  # certbot:
  #     image: certbot/certbot
  #     volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #     command: certonly --webroot --webroot-path=/var/www/certbot/ --email five.realities@gmail.com --agree-tos --no-eff-email -d malone.guru
  #     depends_on:
  #     - nginx

networks:
  dbnet:
    driver: bridge

volumes:
  postgres_volume: