# Generated by Django 5.1.2 on 2024-10-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekevents',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='weekevents',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='weekevents',
            name='week_number',
            field=models.IntegerField(),
        ),
    ]
