# Generated by Django 5.1.2 on 2026-08-14 08:24

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("content", django_ckeditor_5.fields.CKEditor5Field()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
