# Generated by Django 5.1.2 on 2024-10-11 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_weekevents_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayevents',
            name='chef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.chef'),
        ),
        migrations.AlterField(
            model_name='dayevents',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.lecturer'),
        ),
        migrations.AlterField(
            model_name='weekevents',
            name='start_date',
            field=models.DateField(unique=True),
        ),
    ]
