# Generated by Django 5.1.2 on 2024-10-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_alter_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dayevents',
            name='chef',
        ),
        migrations.RemoveField(
            model_name='dayevents',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='dayevents',
            name='week_events',
        ),
        migrations.DeleteModel(
            name='Chef',
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
        migrations.DeleteModel(
            name='DayEvents',
        ),
        migrations.DeleteModel(
            name='WeekEvents',
        ),
    ]
